/** Keep in sync with shared/partner-sync.ts */
var XGOO_EXTENSION_MESSAGE_TYPE = "XGOO_PARTNER_SYNC_V1";
var XGOO_EXTENSION_PING = "XGOO_EXTENSION_PING";
var XGOO_EXTENSION_PONG = "XGOO_EXTENSION_PONG";
var XGOO_EXTENSION_STORED = "XGOO_EXTENSION_STORED";
var XGOO_STORAGE_KEY = "xgoo_pending_payload";
var XGOO_PAYLOAD_MAX_AGE_MS = 30 * 60 * 1000;
